import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.ts',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-fixed': '#ffdcc5',
        'on-secondary': '#ffffff',
        'outline-variant': '#c0c8c2',
        'tertiary-fixed-dim': '#c8c5ca',
        'on-tertiary-fixed': '#1b1b1e',
        'secondary': '#805533',
        'surface-container-high': '#e9e8e5',
        'surface-variant': '#e3e2e0',
        'surface-bright': '#faf9f6',
        'surface-container-highest': '#e3e2e0',
        'tertiary-container': '#454448',
        'inverse-surface': '#2f312f',
        'on-background': '#1a1c1a',
        'primary': '#023626',
        'secondary-container': '#fdc39a',
        'on-primary-fixed': '#002115',
        'on-secondary-container': '#794e2e',
        'error-container': '#ffdad6',
        'background': '#faf9f6',
        'surface-container': '#efeeeb',
        'on-primary-fixed-variant': '#214f3d',
        'tertiary': '#2e2e31',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'inverse-primary': '#a1d1b9',
        'primary-container': '#1f4d3b',
        'on-error-container': '#93000a',
        'surface-tint': '#3a6754',
        'error': '#ba1a1a',
        'surface': '#faf9f6',
        'tertiary-fixed': '#e4e1e6',
        'primary-fixed': '#bcedd5',
        'on-surface': '#1a1c1a',
        'secondary-fixed-dim': '#f4bb92',
        'on-primary-container': '#8dbda6',
        'on-tertiary-container': '#b3b1b5',
        'surface-container-low': '#f4f3f1',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dbdad7',
        'on-secondary-fixed': '#301400',
        'on-secondary-fixed-variant': '#653d1e',
        'primary-fixed-dim': '#a1d1b9',
        'on-surface-variant': '#414944',
        'on-tertiary-fixed-variant': '#47464a',
        'outline': '#717974',
        'inverse-on-surface': '#f2f1ee',
      },
      fontFamily: {
        'body-lg': ['var(--font-inter)'],
        'body-md': ['var(--font-inter)'],
        'headline-lg': ['var(--font-manrope)'],
        'headline-md': ['var(--font-manrope)'],
        'display-xl': ['var(--font-manrope)'],
        'display-xl-mobile': ['var(--font-manrope)'],
        'headline-lg-mobile': ['var(--font-manrope)'],
        'label-sm': ['var(--font-inter)'],
        'mono-sm': ['var(--font-jetbrains-mono)'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'mono-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-xl-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'display-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['30px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        base: '8px',
        'container-max': '1280px',
        'margin-desktop': '64px',
        'margin-mobile': '24px',
        gutter: '24px',
        'section-gap': '120px',
      },
    },
  },
  plugins: [],
}

export default config
